before:
  hooks:
    - go mod download

builds:
  - id: go-verfploeter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: go-verfploeter
    package_name: go-verfploeter
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: Nate Sales
    maintainer: Nate Sales <nate@natesales.net>
    description: Verfploeter implementation in Go
    license: MIT
    section: utils
    priority: extra
    builds:
      - go-verfploeter
    formats:
      - deb
